// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm4niyY48EDbrgNfvKtEjkBDGj74UCDXo',
    appId: '1:982626920448:web:2d29ccf4b20d6f2e73d0e5',
    messagingSenderId: '982626920448',
    projectId: 'flutter-class-b9d70',
    authDomain: 'flutter-class-b9d70.firebaseapp.com',
    storageBucket: 'flutter-class-b9d70.appspot.com',
    measurementId: 'G-S9D6YR18J7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVStdvx-yi2NHTQT7AKcuRfqU1YBFxfKQ',
    appId: '1:982626920448:android:2b34b3d01b871bd473d0e5',
    messagingSenderId: '982626920448',
    projectId: 'flutter-class-b9d70',
    storageBucket: 'flutter-class-b9d70.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCo-drRU_HcFNtovw2EUlKka7ArVRllnSA',
    appId: '1:982626920448:ios:4c5b93700669fd1a73d0e5',
    messagingSenderId: '982626920448',
    projectId: 'flutter-class-b9d70',
    storageBucket: 'flutter-class-b9d70.appspot.com',
    iosBundleId: 'com.hd.todo',
  );
}
